/*  P002: Even Fibonacci Numbers

    Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
    By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89,...
    considering the terms in the Fibonacci sequence whose values do not exceed four million,
    find the sum of the even-valued terms.*/

#include <iostream>
using namespace std;

int main() {
    const int MAX = 4000000;
    int fib[1000];                   // stores fibonacci vals
    int sum = 2;

    fib[0] = 1;
    fib[1] = 2;

    cout << fib[0] << ' ' << fib[1];

    for (int i = 2; fib[i-1] + fib[i-2] < MAX-2; i++) {
        fib[i] = fib[i-1] + fib[i-2];
        
        if (fib[i] % 2 == 0) {
            sum += fib[i];
        }
        cout << ' ' << fib[i];
    }

    cout << " sum: " << sum << endl;

    return 0;
}